version: "3.9"
services:
  runtime_python:
    image: python:3.11-slim
    container_name: data-platform-runtime-python
    working_dir: /app

    volumes:
      - ../pipelines:/app/pipelines
      - ../data-lake:/app/data-lake
    
    env_file:
      - .env
    
    tty: true